// sveltekit-new/src/routes/about/music/+page.svelte
<script lang="ts">
	console.info('about/music: +page.svelte');

	import type { PageData } from './$types';
	export let data: PageData;

	import { Headline } from '$components/Headline';
	import { TopTracks, TopArtists, LastTrack } from '$slices/Music';

	import * as Tabs from '$primitives/Tabs';
	import { writable } from 'svelte/store';
	import Link from '$components/Link/Link.svelte';
	import * as Popper from '$primitives/Popper';
	import AccessibleIcon from '$components/AccessibleIcon';
	import * as RadioGroup from '$primitives/RadioGroup';
	import Filter from '$assets/Icons/24/filter.svg';
	import Close from '$assets/Icons/24/close.svg';

	const defaultSelected = 'tracks';
	const selected = writable(defaultSelected);

	let timeRange = 1;
	const timeRanges: {
		label: string;
		value: 'short' | 'medium' | 'long';
	}[] = [
		{
			label: 'last 4 Weeks',
			value: 'short'
		},
		{
			label: 'last 6 Months',
			value: 'medium'
		},
		{
			label: 'probably forever',
			value: 'long'
		}
	];

	const topTracksResponses = {
		short: data.topTracksShortResponse,
		medium: data.topTracksMediumResponse,
		long: data.topTrackLongResponse
	};

	const topArtistsResponses = {
		short: data.topArtistsShortResponse,
		medium: data.topArtistsMediumResponse,
		long: data.topArtistsLongResponse
	};
</script>

<Headline containerClass="flex items-end py-8 md:py-16">
	Favorite Music
</Headline>

{#if data.lastTrackResponse}
	<Headline
		as="h2"
		type="quaternary"
		id="current_track"
		containerClass="p-2 bg-white border-b border-mauve-6"
	>
		Last listened on Spotify
	</Headline>

	<LastTrack
		labelledby="current_track"
		lastTrackResponse={data.lastTrackResponse}
		class="border-b bg-white/[.85] border-mauve-6 mb-8 md:mb-16"
	/>
{/if}

<Tabs.Root
	defaultValue={defaultSelected}
	on:valueChange={(e) => ($selected = e.detail.value)}
>
	<p class="p-2 bg-white border-t border-mauve-6">
		Favorite on Spotify <span class="text-mauve-11">
			({timeRanges[timeRange].label})
		</span>
	</p>

	<Tabs.List
		ariaLabel="My Favorite Artists and Tracks on Spotify"
		class="flex p-2 space-x-2 border-t border-mauve-6"
	>
		<Tabs.Trigger
			value="tracks"
			class="flex-grow border border-mauve-12 focus:outline-none ring-mauve-12 focus:ring-1 px-4 py-2 rounded-l-full {$selected ===
			'tracks'
				? 'bg-purple-5'
				: 'bg-white'}"
		>
			<Headline as="h2" unstyled id="top_tracks" type="secondary">
				Tracks
			</Headline>
		</Tabs.Trigger>
		<Tabs.Trigger
			value="artists"
			class="flex-grow border border-mauve-12 focus:outline-none ring-mauve-12 focus:ring-1 px-4 py-2 rounded-r-full {$selected ===
			'artists'
				? 'bg-purple-5'
				: 'bg-white'}"
		>
			<Headline as="h2" unstyled type="secondary" id="top_artists">
				Artists
			</Headline>
		</Tabs.Trigger>
		<Popper.Root defaultOpen={false}>
			<Popper.Trigger
				class="p-2 border border-mauve-12 focus:outline-none ring-mauve-12 focus:ring-1"
			>
				<AccessibleIcon label="Filter Favorites">
					<Filter />
				</AccessibleIcon>
			</Popper.Trigger>
			<Popper.Content
				class="bg-white border border-mauve-12 focus:outline-none ring-mauve-12 focus:ring-1"
				side="bottom"
				align="end"
				sideOffset={8}
				alignOffset={0}
			>
				<Headline
					as="h2"
					id="timeHeadline"
					type="tertiary"
					class="border-b-0"
				>
					Time Range
				</Headline>

				<RadioGroup.Root
					defaultValue={timeRanges[timeRange].value}
					required
					name="time"
					labelledby="timeHeadline"
					orientation="vertical"
					class="p-2"
					on:valueChange={(e) =>
						(timeRange = timeRanges.findIndex(
							(range) => range.value === e.detail.value
						))}
				>
					{#each timeRanges as range}
						<div class="flex mb-2 space-x-2 last:mb-0">
							<RadioGroup.Item
								value={range.value}
								id={range.value}
								class="w-6 h-6 p-1 bg-white border rounded-full b border-mauve-12 focus:outline-none ring-mauve-12 focus:ring-1"
							>
								<RadioGroup.Indicator
									class="block w-full h-full p-1 rounded-full bg-plum-5"
								/>
							</RadioGroup.Item>
							<label
								for={range.value}
								on:click={(e) => e.stopPropagation()}
								class="cursor-pointer "
							>
								{range.label}
							</label>
						</div>
					{/each}
				</RadioGroup.Root>

				<Popper.Close
					class="bg-white absolute top-0 right-0 p-2 -translate-y-[51px] translate-x-[1px] border border-mauve-12 focus:outline-none ring-mauve-12 focus:ring-1"
				>
					<AccessibleIcon label="Close Popover">
						<Close />
					</AccessibleIcon>
				</Popper.Close>
			</Popper.Content>
		</Popper.Root>
	</Tabs.List>
	<Tabs.Content
		value="tracks"
		class="border-t border-b bg-white/[.85] border-mauve-6 focus:outline-none ring-mauve-6 focus:ring-1"
	>
		<TopTracks
			labelledby="top_tracks"
			topTracksResponse={topTracksResponses[timeRanges[timeRange].value]}
		/>
	</Tabs.Content>
	<Tabs.Content
		value="artists"
		class="border-t border-b bg-white/[.85] border-mauve-6 focus:outline-none ring-mauve-6 focus:ring-1"
	>
		<TopArtists
			labelledby="top_artists"
			topArtistsResponse={topArtistsResponses[
				timeRanges[timeRange].value
			]}
		/>
	</Tabs.Content>
</Tabs.Root>

<div class="pt-8 pb-32 text-center md:pt-16">
	<p>Made with:</p>
	<p>
		<Link type="secondary" href="https://spotify.com">Spotify</Link>
		💚
		<Link type="secondary" href="https://supabase.com/">Supabase</Link>
	</p>
</div>

// src/pages/Music/Music.tsx
import React, { useState } from 'react';

import {
    getSupabaseLastTrack,
    getSupabaseTopTracks,
    getSupabaseTopArtists,
} from './api/supabase';

import { useAsync } from '../../hooks';

import {
    LastTrackSection,
    TopTracksSection,
    TopArtistsSection,
} from 'src/slices/MusicSection';
import { MusicSectionHeading } from 'src/components/Music';

import * as Tabs from 'src/components/StyledTabs';
import * as Popover from 'src/components/StyledPopover';
import * as RadioGroup from 'src/components/StyledRadioGroup';
import * as StyledSeperator from 'src/components/StyledSeperator';

import * as Icon from 'src/components/Icon';
import { status } from '../../types';
import { AccessibleIcon } from '@radix-ui/react-accessible-icon';

const Music: React.FC = () => {
    const lastTrackState = useAsync({
        status: status.pending,
    });
    React.useEffect(() => {
        const promise = getSupabaseLastTrack();
        lastTrackState.run(promise);
    }, [lastTrackState.run]);

    const topTracksState = useAsync({
        status: status.pending,
    });

    React.useEffect(() => {
        const promise = getSupabaseTopTracks();
        topTracksState.run(promise);
    }, [topTracksState.run]);

    React.useEffect(() => {
        console.log(lastTrackState);
    }, [lastTrackState.status]);
    const topArtistsState = useAsync({
        status: status.pending,
    });

    React.useEffect(() => {
        const promise = getSupabaseTopArtists();
        topArtistsState.run(promise);
    }, [topArtistsState.run]);

    const [selected, setSelected] = useState('tracks');

    const ranges = ['short', 'medium', 'long'];
    const [range, setRange] = useState('short');

    return (
        <main className="my-16">
            <div className="grid grid-cols-[60px,1fr,fit-content(100%),1fr,60px] md:grid-cols-[84px,1fr,fit-content(100%),1fr,84px] my-16 items-center">
                <h1 className="col-start-3 font-cstmx text-6xl md:text-8xl lg:text-10xl">
                    MUSIC
                </h1>
                <div className="col-start-1 col-span-4 border-mauve-12 border-t" />
            </div>
            <div className="my-16">
                <div className="ml-[60px] md:ml-[84px] p-2 border-l border-t border-mauve-12 bg-mauve-3">
                    <MusicSectionHeading>Current Track</MusicSectionHeading>
                </div>
                <LastTrackSection lastTrackState={lastTrackState} />
            </div>
            <Tabs.Root
                defaultValue={selected}
                onValueChange={(value) => setSelected(value)}>
                <Tabs.List>
                    <Tabs.Trigger value="tracks" selected={selected}>
                        <MusicSectionHeading>Top Tracks</MusicSectionHeading>
                    </Tabs.Trigger>
                    <Tabs.Trigger
                        className="reversed"
                        value="artists"
                        selected={selected}>
                        <MusicSectionHeading>Top Artists</MusicSectionHeading>
                    </Tabs.Trigger>
                    <Popover.Root>
                        <Popover.Trigger className="md:px-4 border-t border-mauve-12 ">
                            <AccessibleIcon label="Filter Content">
                                <Icon.Filter
                                    active={ranges.findIndex(
                                        (r) => r === range,
                                    )}
                                    fill="icon-purple-5"
                                />
                            </AccessibleIcon>
                        </Popover.Trigger>
                        <Popover.Content className="bg-white">
                            <h3 className="mr-16">Time Range</h3>
                            <StyledSeperator.Root />
                            <RadioGroup.Root
                                defaultValue={range}
                                onValueChange={(value) => setRange(value)}>
                                <RadioGroup.Item value="short">
                                    <RadioGroup.Indicator></RadioGroup.Indicator>
                                    <RadioGroup.Label>Short</RadioGroup.Label>
                                </RadioGroup.Item>
                                <RadioGroup.Item value="medium">
                                    <RadioGroup.Indicator></RadioGroup.Indicator>
                                    <RadioGroup.Label>Medium</RadioGroup.Label>
                                </RadioGroup.Item>
                                <RadioGroup.Item value="long">
                                    <RadioGroup.Indicator></RadioGroup.Indicator>
                                    <RadioGroup.Label>Long</RadioGroup.Label>
                                </RadioGroup.Item>
                            </RadioGroup.Root>
                            <Popover.Close />
                        </Popover.Content>
                    </Popover.Root>
                </Tabs.List>
                <Tabs.Content className="" value="tracks">
                    <TopTracksSection
                        topTracksState={topTracksState}
                        range={ranges.findIndex((r) => r === range)}
                    />
                </Tabs.Content>
                <Tabs.Content value="artists">
                    <TopArtistsSection
                        topArtistsState={topArtistsState}
                        range={ranges.findIndex((r) => r === range)}
                    />
                </Tabs.Content>
            </Tabs.Root>
            <p className="my-16 text-center">
                Made with by{' '}
                <a
                    href="https://spotify.com"
                    className="text-mauve-12 underline"
                    rel="noopener noreferrer"
                    target="_blank">
                    Spotify
                </a>
                {' 💚 '}
                <a
                    href="https://supabase.com/"
                    className="text-mauve-12 underline"
                    rel="noopener noreferrer"
                    target="_blank">
                    Supabase
                </a>{' '}
            </p>
        </main>
    );
};

export default Music;
