// react/src/slices/MusicSection/TopArtistsSection.tsx
import React from 'react';

import {
    MusicSectionRoot,
    MusicSectionBody,
    MusicSectionRow,
    MusicSectionAtom,
    MusicSectionImage,
    MusicSectionDetail,
    MusicSectionLoading,
    MusicSectionError,
} from '../../components/Music';
import { ExternalLink } from 'src/components/ExternalLink';
import { Tag, Score } from 'src/components/Icon';

import { topArtist, status, asyncState } from 'src/types';

export const TopArtistsSection: React.FC<{
    topArtistsState: asyncState;
    range: number;
}> = ({ topArtistsState, range }) => {
    switch (topArtistsState.status) {
        case status.idle:
        case status.pending:
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        <MusicSectionLoading length={8} />
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        case status.rejected:
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        <MusicSectionError
                            length={8}
                            message={topArtistsState.error.message}
                        />
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        case status.resolved: {
            const topArtists = (topArtistsState.data[range] ||
                []) as topArtist[];
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        {topArtists.length > 0 &&
                            topArtists.map((artist) => (
                                <MusicSectionRow
                                    className="flex"
                                    key={artist.id}>
                                    {artist.images.length > 0 && (
                                        <MusicSectionAtom>
                                            <ExternalLink
                                                href={
                                                    artist.external_urls.spotify
                                                }
                                                ghost>
                                                <MusicSectionImage
                                                    url={
                                                        artist.images[
                                                            artist.images
                                                                .length - 1
                                                        ].url
                                                    }
                                                    alt={`${artist.name} Artist Image`}
                                                />
                                            </ExternalLink>
                                        </MusicSectionAtom>
                                    )}
                                    <MusicSectionAtom className="flex-1 p-2 border-l border-mauve-12 min-w-0">
                                        <MusicSectionDetail
                                            headline={
                                                <ExternalLink
                                                    href={
                                                        artist.external_urls
                                                            .spotify
                                                    }>
                                                    {artist.name}
                                                </ExternalLink>
                                            }
                                            subline={[
                                                artist.genres.join(', '),
                                                `${artist.popularity} / 100`,
                                            ]}>
                                            <Tag
                                                fill="icon-mauve-5"
                                                width={20}
                                                height={20}
                                            />
                                            <Score
                                                id={artist.id}
                                                score={artist.popularity}
                                                fill="icon-mauve-5"
                                                width={20}
                                                height={20}
                                            />
                                        </MusicSectionDetail>
                                    </MusicSectionAtom>
                                </MusicSectionRow>
                            ))}
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        }
        default:
            throw new Error('This should be impossible');
    }
};

// sveltekit-test/src/lib/Slices/Music/TopArtistsSection.svelte
<script lang="ts">
	import * as Music from '$components/Music';
	import { Link } from '$components/Link';
	import type { SpotifyTopArtistsResponse, Image } from 'src/routes/about/types';

	export let topArtistsResponse: SpotifyTopArtistsResponse;
	console.log(topArtistsResponse);

	const valid = (() => {
		if (topArtistsResponse.ok) return true;
		if (!topArtistsResponse.ok) return false;
		return undefined;
	})();

	import Tag from '$assets/Icons/24/Tag.svg';
	import Score from '$assets/Icons/24/Score.svg';
	console.log(topArtistsResponse);

	const getImageUrl = (images: Image[]): string => {
		if (images.length === 0) return '';

		const targetSize = 92;
		const currentSize = images[0].height;
		let targetIndex = 0;

		for (let i = 1; i < images.length; i++) {
			const image = images[i];
			if (image.height > 92 && image.height - targetSize < currentSize - targetSize) {
				targetIndex = i;
			}
		}

		return images[targetIndex].url;
	};
</script>

{#if valid === true && 'items' in topArtistsResponse.body}
	<Music.Root>
		{#each topArtistsResponse.body.items as artist (artist.id)}
			<Music.Row class="flex">
				{#if artist.images.length}
					<Music.Atom>
						<Link href={artist.external_urls.spotify} type="ghost">
							<Music.Image url={getImageUrl(artist.images)} alt={`${artist.name}`} /></Link
						>
					</Music.Atom>
				{/if}
				<Music.Atom class="flex-1 min-w-0 border-l border-mauve-5">
					<Music.Detail subline={[artist.genres.join(', '), `${artist.popularity} / 100`]}>
						<Tag slot="preline" />

						<Link href={artist.external_urls.spotify}>
							{artist.name}
						</Link>

						<Score slot="subline" />
					</Music.Detail>
				</Music.Atom>
			</Music.Row>
		{/each}
	</Music.Root>
{:else if valid === false && 'error' in topArtistsResponse.body}
	{#if typeof topArtistsResponse.body.error === 'string'}
		<p>{topArtistsResponse.body.error}</p>
	{:else if typeof topArtistsResponse === 'object'}
		<p>{topArtistsResponse.body.error.status} {topArtistsResponse.body.error.message}</p>
	{/if}
{/if}
