// react/src/slices/MusicSection/TopTracksSection.tsx
import React from 'react';

import {
    MusicSectionRoot,
    MusicSectionBody,
    MusicSectionRow,
    MusicSectionAtom,
    MusicSectionImage,
    MusicSectionDetail,
    MusicSectionLoading,
    MusicSectionError,
} from '../../components/Music';
import { ExternalLink } from 'src/components/ExternalLink';
import { Artist, Album } from 'src/components/Icon';

import { topTrack, status, asyncState } from 'src/types';

export const TopTracksSection: React.FC<{
    topTracksState: asyncState;
    range: number;
}> = ({ topTracksState, range }) => {
    switch (topTracksState.status) {
        case status.idle:
        case status.pending:
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        <MusicSectionLoading length={8} />
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        case status.rejected:
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        <MusicSectionError
                            length={8}
                            message={topTracksState.error.message}
                        />
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        case status.resolved: {
            const topTracks = (topTracksState.data[range] || []) as topTrack[];
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        {topTracks.length > 0 &&
                            topTracks.map((track) => (
                                <MusicSectionRow
                                    className="flex"
                                    key={track.id}
                                >
                                    {track.album.images.length > 0 && (
                                        <MusicSectionAtom>
                                            <ExternalLink
                                                href={
                                                    track.external_urls.spotify
                                                }
                                                ghost
                                            >
                                                <MusicSectionImage
                                                    url={
                                                        track.album.images[0]
                                                            .url
                                                    }
                                                    alt={`${track.album.name} Album Cover`}
                                                />
                                            </ExternalLink>
                                        </MusicSectionAtom>
                                    )}
                                    <MusicSectionAtom className="flex-1 p-2 border-l border-mauve-12 min-w-0">
                                        <MusicSectionDetail
                                            headline={
                                                <ExternalLink
                                                    href={
                                                        track.external_urls
                                                            .spotify
                                                    }
                                                >
                                                    {track.name}
                                                </ExternalLink>
                                            }
                                            subline={[
                                                track.artists
                                                    .map(
                                                        (artist) => artist.name,
                                                    )
                                                    .join(', '),
                                                track.album.name,
                                            ]}
                                        >
                                            <Artist
                                                fill="icon-mauve-5"
                                                width={20}
                                                height={20}
                                            />
                                            <Album
                                                fill="icon-mauve-5"
                                                width={20}
                                                height={20}
                                            />
                                        </MusicSectionDetail>
                                    </MusicSectionAtom>
                                </MusicSectionRow>
                            ))}
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        }
        default:
            throw new Error('This should be impossible');
    }
};

// sveltekit-test/src/lib/Slices/Music/TopTracksSection.svelte
<script lang="ts">
	import * as Music from '$components/Music';
	import type { SpotifyTopTracksResponse } from 'src/routes/about/types';

	export let topTracksResponse: SpotifyTopTracksResponse;
	console.log(topTracksResponse);

	const valid = (() => {
		if (topTracksResponse.ok) return true;
		if (!topTracksResponse.ok) return false;
		return undefined;
	})();

	import Album from '$assets/Icons/24/Album.svg';
	import Artist from '$assets/Icons/24/Artist.svg';
</script>

{#if valid === true && 'items' in topTracksResponse.body}
	<Music.Root>
		{#each topTracksResponse.body.items as track (track.id)}
			<Music.Row class="flex">
				{#if track.album.images.length}
					<Music.Atom>
						<!--ExternalLink
                                href={
                                    track.external_urls.spotify
                                }
                                ghost
                            -->
						<Music.Image url={track.album.images[0].url} alt={`${track.album.name} Album Cover`} />
					</Music.Atom>
				{/if}
				<Music.Atom class="flex-1 min-w-0 p-2 border-l border-mauve-5">
					<Music.Detail
						subline={[track.artists.map((artist) => artist.name).join(', '), track.album.name]}
					>
						<!--ExternalLink href={track.external_urls.spotify}>
					</ExternalLink-->
						<Artist slot="subline" />
						{track.name}
						<Album slot="preline" />
					</Music.Detail>
				</Music.Atom>
			</Music.Row>
		{/each}
	</Music.Root>
{:else if valid === false && 'error' in topTracksResponse.body}
	{#if typeof topTracksResponse.body.error === 'string'}
		<p>{topTracksResponse.body.error}</p>
	{:else if typeof topTracksResponse === 'object'}
		<p>{topTracksResponse.body.error.status} {topTracksResponse.body.error.message}</p>
	{/if}
{/if}
