// sveltekit-test/src/lib/Slices/Music/LastTrackSection.svelte
<script lang="ts">
	import * as Music from '$components/Music';
	import { Link } from '$components/Link';
	import type { SpotifyLastTrackResponse, Image } from 'src/routes/about/types';

	export let lastTrackResponse: SpotifyLastTrackResponse;

	const track = 'item' in lastTrackResponse.body ? lastTrackResponse.body.item : undefined;

	const valid = (() => {
		if (lastTrackResponse.ok) return true;
		if (!lastTrackResponse.ok) return false;
		return undefined;
	})();

	import Album from '$assets/Icons/24/Album.svg';
	import Artist from '$assets/Icons/24/Artist.svg';

	const getImageUrl = (images: Image[]): string => {
		if (images.length === 0) return '';

		const targetSize = 92;
		const currentSize = images[0].height;
		let targetIndex = 0;

		for (let i = 1; i < images.length; i++) {
			const image = images[i];
			if (image.height > 92 && image.height - targetSize < currentSize - targetSize) {
				targetIndex = i;
			}
		}

		return images[targetIndex].url;
	};
</script>

{#if valid === true && 'item' in lastTrackResponse.body}
	<Music.Root>
		<Music.Row class="flex">
			{#if track.album.images.length}
				<Music.Atom>
					<Link href={track.external_urls.spotify} type="ghost">
						<Music.Image
							url={getImageUrl(track.album.images)}
							alt={`${track.album.name} Album Cover`}
						/></Link
					>
				</Music.Atom>
			{/if}
			<Music.Atom class="flex-1 min-w-0 border-l border-mauve-5">
				<Music.Detail
					subline={[track.artists.map((artist) => artist.name).join(', '), track.album.name]}
				>
					<Artist slot="preline" />
					<Link href={track.external_urls.spotify}>
						{track.name}
					</Link>
					{#if 'is_playable' in track}
						<MusicSectionPlaying slot="headline" />
					{/if}

					<Album slot="subline" />
				</Music.Detail>
			</Music.Atom>
		</Music.Row>
	</Music.Root>
{:else if valid === false && 'error' in lastTrackResponse.body}
	{#if typeof lastTrackResponse.body.error === 'string'}
		<p>{lastTrackResponse.body.error}</p>
	{:else if typeof lastTrackResponse === 'object'}
		<p>{lastTrackResponse.body.error.status} {lastTrackResponse.body.error.message}</p>
	{/if}
{/if}

// react/src/slices/MusicSection/LastTrackSection.tsx
import React from 'react';

import {
    MusicSectionRoot,
    MusicSectionBody,
    MusicSectionRow,
    MusicSectionAtom,
    MusicSectionImage,
    MusicSectionDetail,
    MusicSectionLoading,
    MusicSectionPlaying,
    MusicSectionError,
} from '../../components/Music';
import { ExternalLink } from 'src/components/ExternalLink';
import { Artist, Album } from 'src/components/Icon';

import { currentTrack, recentTrack, status, asyncState } from 'src/types';

export const LastTrackSection: React.FC<{
    lastTrackState: asyncState;
}> = ({ lastTrackState }) => {
    console.log(lastTrackState.status);
    switch (lastTrackState.status) {
        case status.idle:
        case status.pending:
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        <MusicSectionLoading length={1} />
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        case status.rejected:
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        <MusicSectionError
                            length={1}
                            message={lastTrackState.error.message}
                        />
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        case status.resolved: {
            const lastTrack = lastTrackState.data[0] as
                | currentTrack[]
                | recentTrack[];
            return (
                <MusicSectionRoot>
                    <MusicSectionBody>
                        {lastTrack.length > 0 &&
                            lastTrack.map((track) => (
                                <MusicSectionRow
                                    className="flex"
                                    key={track.id}>
                                    {track.album.images.length > 0 && (
                                        <MusicSectionAtom>
                                            <ExternalLink
                                                href={
                                                    track.external_urls.spotify
                                                }
                                                ghost>
                                                <MusicSectionImage
                                                    url={
                                                        track.album.images[0]
                                                            .url
                                                    }
                                                    alt={`${track.album.name} Album Cover`}
                                                />
                                            </ExternalLink>
                                        </MusicSectionAtom>
                                    )}
                                    <MusicSectionAtom className="flex-1 p-2 border-l border-mauve-12 min-w-0 md:pr-8 xl:pr-16">
                                        <MusicSectionDetail
                                            headline={
                                                <ExternalLink
                                                    href={
                                                        track.external_urls
                                                            .spotify
                                                    }>
                                                    {track.name}
                                                </ExternalLink>
                                            }
                                            subline={[
                                                track.artists
                                                    .map(
                                                        (artist) => artist.name,
                                                    )
                                                    .join(', '),
                                                track.album.name,
                                            ]}>
                                            <Artist
                                                fill="icon-mauve-5"
                                                width={20}
                                                height={20}
                                            />
                                            <Album
                                                fill="icon-mauve-5"
                                                width={20}
                                                height={20}
                                            />
                                            {track.hasOwnProperty(
                                                'is_playable',
                                            ) && <MusicSectionPlaying />}
                                        </MusicSectionDetail>
                                    </MusicSectionAtom>
                                </MusicSectionRow>
                            ))}
                    </MusicSectionBody>
                </MusicSectionRoot>
            );
        }
        default:
            throw new Error('This should be impossible');
    }
};
