// src/components/ExternalLink/ExternalLink.tsx
import React from 'react';

const ExternalLink: React.FC<{
    href: string;
    ghost?: boolean;
    children: React.ReactNode;
    className?: string;
}> = ({ ghost = false, href = '', children, className = '' }) => {
    return (
        <a
            href={href}
            target="_blank"
            rel="noopener nofollow"
            tabIndex={ghost ? -1 : 0}
            className={`focus:outline-none ${
                ghost ? '' : 'growing-underline'
            } ${className}`}>
            {children}
        </a>
    );
};

export default ExternalLink;

// sveltekit/src/lib/components/ExternalLink/ExternalLink.svelte
<script lang="ts">
    import { ExternalLinkTypes } from "./index";

    export let href: string;
    export let type: ExternalLinkTypes;
    export const ghost: boolean = false;
    let c: string = '';
    export { c as class };
</script>

<a
    href={href}
    target="_blank"
    rel="noopener nofollow"
    tabIndex={ghost ? -1 : 0}
    class={`focus:outline-none 
        ${type === ExternalLinkTypes.underline ? 'underline' : ''}
        ${type === ExternalLinkTypes.growingUnderline ? 'growing-underline' : ''}
        ${c}`}
>
    <slot />
</a>
